# Rever as configs de arquivos utilizando o link abaixo
# https://docs.docker.com/compose/compose-file/#configs-top-level-element

services:
  # Imagem base utilizada.
  # Verifique o Dockerfile para saber o que está sendo instalado.
  base:
    container_name: base-image
    image: "${CLIENT_NAME}/base-tools"
    working_dir: /root
    build:
      context: .
      args:
        ARCH: ${ARCH:-linux/amd64}
    volumes:
      # Configurações para Bash onde existem algumas personalizações
      - ./configs/.bashrc:/root/.bashrc
      - ./configs/.bash_aliases:/root/.bash_aliases
      - ./configs/.bash_colors:/root/.bash_colors

      # Configurações para Git
      - ./configs/.gitconfig:/root/.gitconfig

      # Configurações para Vim
      - ./configs/.vimrc:/root/.vimrc

      - ./configs/.inputrc:/root/.inputrc
      - ./bootstrap/install-packages.sh:/root/install-packages.sh

      # Configuração do ambiente para selecionar apenas o que desejar
      - ./.env.config:/root/.env.config

      # File system em read only.
      # No momento nao é possivel utilizar como secret o diretorio .ssh, problemas
      # com permissionamento quando executar git push retorando bad permissions por
      # ser aberto demais.
      - ${HOME}/.ssh/${CLIENT_NAME}:/root/.ssh:rw
    network_mode: host

  # docker-compose run install-tools
  install-tools:
    # Quando iniciar o container, automaticamente será chamado o script para fazer
    # intalação de todas ferramentas ali definidas.
    command: bash /tmp/bootstrap.sh
    extends:
      service: base
    volumes:
      # Este arquivo faz a instalação do que for definido nele. Geralmente apenas
      # chamamos o nome da função que desejamos instalar. Os scripts de instalação
      # das ferramentas em si estão em volume no arquivo commom.yml
      - ./bootstrap/bootstrap.sh:/tmp/bootstrap.sh

  # Template utilizado pela maioria dos containers que rodam bash.
  # Toda a base do que deverá ter no container está vindo do arquivo commom.yml
  docker-template-base:
    container_name: docker-template-base

    extends:
      service: base
    volumes:
      # Arquivos para linha de comando
      - ./cli:/root/cli
      - ./cli/cli.sh:/usr/bin/cli
    stdin_open: true
    tty: true
    mem_limit: 1024M
    network_mode: host
